### ISSUE TITLE
Add some explanatory text to login and signup on what the service does

### ISSUE THREAD

**Issue by Russell-Pollari** [Daniel-olaO/nasa-client#23]
On both the login and signup screens, add a short line to explain to people what they are signing up for

e.g.
"Get Nasa's Astronomy Picture of the day texted to your phone every day"

**Comment by Daniel-olaO** [comment]
UX question: where should I position the app-info in relation to the forms

**Comment by Russell-Pollari** [comment]
Above the form IMO
