### ISSUE TITLE
Add more context to subsctription status

### ISSUE THREAD

**Issue by Russell-Pollari** [Daniel-olaO/nasa-client#24]
The copy "You are not subscribed to nasa APOD" should be more verbose.

e.g.
You are currently subscribed. You will get a text with Nasa's Astronomy Picture of the Day every day at {time}

You are currently unsubscribed. Subscribe below to get a text with Nasa's Astronomy Picture of the Day every day at {time}

**Comment by Daniel-olaO** [comment]
Let me try and see if I can specify a time for the sender function in the API
